### PR TITLE
add prop-types as dependency for #90

### LINKED ISSUE #90: undefined is not an object (evaluating '_react2.PropTypes.string')
Hey! I'm trying to run the example code in the ReadMe and am getting this error.

### PR DESCRIPTION
**Pull request by Noitidart**
Fixes #90

### CODE REVIEW

**Comment by Noitidart** [comment]
also closes #87

**Comment by prscX** [comment]
Hi @cnjon 

Can you merge this PR, basically React as deprecated importing of PropTypes from react:

`import React, {Component, PropTypes} from "react";` 

They have created a separate node module prop-type for the same:

`import PropTypes from 'prop-types'`

In ReactNative >=0.49.0 it is throwing exception due to which app is not working

Can you please approve this merge request, so that in next release onwards we can get the fix for the same

Please let me know in case any discussion is needed

Thanks
Pranav

**Comment by icaromagalhaes** [comment]
Any updates on this merge?

**Comment by prscX** [comment]
Hi @cnjon, Can you please merge this PR. For each `yarn install` we are getting this error which is very annoyance.

Please let me know in case any discussion is required for the same.

Thanks
Pranav

**Comment by marcorm** [comment]
Hi @cnjon, could you please merge this PR?

Thanks for your work!
Marco

**Comment by ue** [comment]
I came here for adding the PropType 💃 🤣  Thanx for your work 👍

**Comment by prscX** [comment]
Thanks @sibelius for merging the PR 😄 

Can you please publish the same on NPM as well.

Thanks
</ Pranav >

**Pull request merged**
