### PR TITLE
fixed React Native 0.40 headers

### PR DESCRIPTION
**Pull request by horsekitlin**
for issue #37

### CODE REVIEW

**Comment by mehcode** [comment]
@cnjon Can we get this merged?

**Comment by gyzerok** [comment]
@cnjon merge it, please

**Comment by gyzerok** [comment]
@sibelius hi, maybe you can help with this?

**Comment by sibelius** [comment]
tks, @cnjon can u do a breaking bump?

**Comment by marcosinigaglia** [comment]
Is there a new release?

**Pull request merged**
